export const KEY_STATUSES = [
  "KALSHI_DEMO_CONFIGURED",
  "KALSHI_PROD_CONFIGURED",
  "KALSHI_DEMO_API_KEY_PRESENT",
  "KALSHI_DEMO_PRIVATE_KEY_PRESENT",
  "KALSHI_DEMO_PAIR_CONFIGURED",
  "KALSHI_PROD_API_KEY_PRESENT",
  "KALSHI_PROD_PRIVATE_KEY_PRESENT",
  "KALSHI_PROD_PAIR_CONFIGURED",
  "KALSHI_AUTH_TEST_PASSED",
  "KALSHI_AUTH_TEST_FAILED",
  "ODDS_API_CONFIGURED",
  "KEY_MISSING",
  "KEY_INVALID",
  "KEY_DISABLED",
  "KEY_EXPIRED_OR_REVOKED",
  "KEY_PERMISSION_ERROR",
  "KEY_QUOTA_LOW",
  "KEY_QUOTA_EXHAUSTED",
  "NOT_CONFIGURED",
  "TEST_PENDING",
] as const;

export const KALSHI_ERROR_CATEGORIES = [
  "KALSHI_NETWORK_ERROR",
  "KALSHI_SIGNING_ERROR",
  "KALSHI_AUTH_REJECTED",
  "DEMO_PROD_KEY_MISMATCH",
  "KALSHI_KEY_PAIR_INCOMPLETE",
  "KALSHI_PRIVATE_KEY_FORMAT_ERROR",
  "KALSHI_BASE_URL_UNCONFIRMED",
] as const;

export type KalshiErrorCategory = (typeof KALSHI_ERROR_CATEGORIES)[number];

export type SecureKeyStatus = (typeof KEY_STATUSES)[number];

export const KEY_BLOCK_CODES = {
  ODDS_API_KEY_MISSING: "BLOCKED — ODDS_API_KEY_MISSING",
  KALSHI_PROD_KEY_MISSING: "BLOCKED — KALSHI_PROD_KEY_MISSING",
  KALSHI_PRIVATE_KEY_MISSING: "BLOCKED — KALSHI_PRIVATE_KEY_MISSING",
  SECRET_EXPOSED_CLIENT_SIDE: "BLOCKED — SECRET_EXPOSED_CLIENT_SIDE",
  PRODUCTION_KEYS_NOT_CONFIGURED: "BLOCKED — PRODUCTION_KEYS_NOT_CONFIGURED",
  DEMO_PROD_KEY_MISMATCH: "BLOCKED — DEMO_PROD_KEY_MISMATCH",
  KALSHI_KEY_PAIR_INCOMPLETE: "KALSHI_KEY_PAIR_INCOMPLETE",
  KALSHI_PRIVATE_KEY_FORMAT_ERROR: "KALSHI_PRIVATE_KEY_FORMAT_ERROR",
  KALSHI_NETWORK_ERROR: "KALSHI_NETWORK_ERROR",
  KALSHI_SIGNING_ERROR: "KALSHI_SIGNING_ERROR",
  KALSHI_AUTH_REJECTED: "KALSHI_AUTH_REJECTED",
  KALSHI_BASE_URL_UNCONFIRMED: "KALSHI_BASE_URL_UNCONFIRMED",
  MULTIPLE_KEY_POLICY_NOT_CONFIRMED: "BLOCKED — MULTIPLE_KEY_POLICY_NOT_CONFIRMED",
  PROVIDER_KEYS_MUST_BE_CREATED_IN_PROVIDER_DASHBOARD:
    "PROVIDER_KEYS_MUST_BE_CREATED_IN_PROVIDER_DASHBOARD",
} as const;

export const SANITIZED_KEY_RESPONSE_FIELDS = [
  "id",
  "label",
  "provider",
  "maskedPreview",
  "enabled",
  "environment",
  "status",
  "updatedAt",
  "lastTestedAt",
  "quotaStatus",
  "errorCategory",
] as const;
