import type { ScoredOpportunity } from "../../src/lib/core/types.js";

export function mockOpportunity(overrides: Partial<ScoredOpportunity> = {}): ScoredOpportunity {
  return {
    id: "test-opp-1",
    sport: "basketball_nba",
    league: "NBA",
    game: "Lakers vs Celtics",
    teams: { home: "Los Angeles Lakers", away: "Boston Celtics" },
    startTime: new Date(Date.now() + 3600_000).toISOString(),
    liveStatus: "PRE_GAME",
    kalshiEvent: "KXNBAGAME",
    kalshiMarket: "Lakers to win",
    kalshiTicker: "KXNBAGAME-LAL",
    sportsbookEvent: "evt-1",
    sportsbookMarket: "h2h",
    side: "YES",
    matchConfidence: "HIGH",
    settlementConfidence: "EXACT",
    marketTypeLevel: "LEVEL_1_DIRECT_COMPARABLE",
    scopePeriod: "FULL_GAME",
    overtimeTreatment: "OVERTIME_INCLUDED",
    currentScore: null,
    clockPeriod: null,
    executableKalshiAsk: 0.45,
    orderbookFreshness: "FRESH",
    oddsFreshness: "FRESH",
    scoreFreshness: "N/A",
    noVigFairProbability: 0.52,
    bookmakerCount: 3,
    sportsbookDisagreement: 0.02,
    liquidity: "HIGH",
    fillableNotional: 500,
    edgeBreakdown: {
      grossEdge: 0.07,
      fees: 0.005,
      spread: 0.01,
      slippage: 0.005,
      staleDataBuffer: 0.005,
      partialFillRisk: 0.005,
      confidencePenalty: 0.005,
      netEdge: 0.05,
      edgeTier: "NORMAL_EDGE",
      blockCode: null,
    },
    expectedDollarProfit: 2.5,
    expectedProfitPerSecond: 0.001,
    expectedProfitPerMinute: 0.05,
    edgeSurvivalConfidence: 0.85,
    fillProbability: 0.9,
    edgeQualityScore: 72,
    moneyConfidenceScore: 68,
    profitPriorityScore: 60,
    userRequestedStake: 10,
    aiRecommendedStake: 5,
    finalAllowedStake: 5,
    maxLoss: 5,
    state: "BETTABLE",
    reason: "Verified edge",
    highMarginStatus: "NOT_APPLICABLE",
    valueBucket: "TARGET_EDGE",
    executeReadiness: "PER_TRADE_VALIDATION_REQUIRED",
    dataLabel: "REAL_PROVIDER_DATA",
    ...overrides,
  };
}
